version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}

      - run:
          name: Install dependencies
          command: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run:
          name: Build and package WAR
          command: mvn clean package -DskipTests=true

      - store_artifacts:
          path: target/your-app.war

  deploy:
    docker:
      - image: circleci/tomcat:9.0-jdk11

    environment:
      TOMCAT_USER: your-tomcat-username
      TOMCAT_PASSWORD: your-tomcat-password
      TOMCAT_URL: http://your-tomcat-server:8080

    steps:
      - checkout

      - run:
          name: Deploy WAR to Tomcat
          command: |
            curl -v -u $TOMCAT_USER:$TOMCAT_PASSWORD \
            -X PUT "$TOMCAT_URL/manager/text/deploy?path=/your-app&war=file:/home/circleci/project/target/your-app.war"
