version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:11
    steps:
      - checkout
      - run:
          name: Build WAR
          command:  mvn clean package 
       - run: 
          name: Deploying WAR
          command: mvn clean package 
