version: 2.1

jobs:
  build:
    docker:
      - image: maven:3.8.4-jdk-11

    steps:
      - checkout

      - run:
          name: Build Maven Project
          command: mvn clean package

      - run:
          name: Deploy to Tomcat
          command: |
            apt-get update && apt-get install -y curl

            # Configure Tomcat credentials
            export TOMCAT_USERNAME=admin
            export TOMCAT_PASSWORD=admin

            # Deploy the WAR file to Tomcat
            curl -v -u admin:admin \
            -X PUT "http://34.239.102.33:8080//manager/text/deploy?path=/webapp&war=file:/root/app/webapp/target/webapp.war"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
