version: 2.1
workflows:
  ci-wf:
    jobs:
      - build-and-deploy

  sched-cd-wf:
    triggers:
      - schedule:
          cron: "0 16 * * 1,2,3,4,5" 
          filters:
            branches:
              only: master
jobs:
  build:
    docker:
      - image: maven:3.8.4-jdk-11

       steps:
         - checkout

         - run:
          name: Build Maven Project
          command: mvn clean package

   build-and-deploy:
        docker:
          - image: maven:3.8.4-jdk-11
          - run:
            name: Deploy to Tomcat
            command: |
            apt-get update && apt-get install -y curl


            # Deploy the WAR file to Tomcat

             curl -v -u admin:admin --upload-file /root/project/webapp/target/webapp.war "http://34.239.102.33:8080/manager/text/deploy?path=/webapp"
