version: 2.1

jobs:
  build:
    docker:
      - image: maven:3.8.4-jdk-11
    working_directory: ~/app

    steps:
      - checkout

      - run:
          name: Build Maven Project
          command: mvn clean package

      - run:
          name: Deploy to Tomcat
          command: |
            apt-get update && apt-get install -y curl

            # Configure Tomcat credentials
            export TOMCAT_USERNAME=<tomcat-username>
            export TOMCAT_PASSWORD=<tomcat-password>

            # Deploy the WAR file to Tomcat
            curl -v -T target/your-application.war "http://$TOMCAT_USERNAME:$TOMCAT_PASSWORD@localhost:8080/manager/text/deploy?path=/your-application"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
