version: 2.1
jobs:
  build:
    docker:
      - image: maven:3.8.4-jdk-11

        steps:
         - checkout

         - run:
            name: Build Maven Project
            command: mvn clean package

  deploy:
        docker:
          - image: maven:3.8.4-jdk-11
          
            steps:
             - deploy
             
             
             - run:
                name: Deploy to Tomcat
                command: |
                  apt-get update && apt-get install -y curl
                  curl -v -u bhanu:bhanu --upload-file "http://3.109.133.42:8080/manager/text/deploy?path=/webapp"
